import catalogJson from "@/data/price-catalog.json";
import { positionCost } from "./internalCosts";

/**
 * All amounts are integer cents, net. Generated by scripts/sync-easybill-positions.mjs.
 *
 * Ohne Einkaufspreise: die stehen in der gitignorierten price-catalog.internal.json
 * und kommen über positionCost() dazu, damit das Repo sie nicht enthält.
 */
export interface CatalogPosition {
  number: string;
  description: string;
  salePrice: number;
  unit: string;
  vatPercent: number;
  tiers: number[];
}

const positions = new Map<string, CatalogPosition>(
  (catalogJson.positions as CatalogPosition[]).map((p) => [p.number, p]),
);

/** easybill position numbers. Keep in sync with the catalog — a typo throws at call time. */
export const POS = {
  barEquipment: "10001", // per barkeeper
  bohEquipment: "10002", // per 50 guests
  glassware: "10003", // per guest
  projectLead: "20001", // day rate
  serviceStaff: "20002", // per hour
  barBack: "20003", // per hour
  barkeeper: "20004", // per hour
  logistics: "20005", // per hour
  logisticsLead: "20006", // per hour
  cocktail: "30001", // per drink
  signatureCocktail: "30002", // per drink
  nitroCocktail: "30003", // per drink
  highball: "30004", // per drink
  softDrinks: "30005", // per guest, covers 5 hours
  fingerfood: "40001", // per guest
  flyingBuffet: "40002", // per guest
  transport: "60006", // flat
  coolingTruck: "80133", // flat
} as const;

export function position(number: string): CatalogPosition {
  const p = positions.get(number);
  if (!p) {
    throw new Error(
      `Position ${number} not found in price-catalog.json. Run: node scripts/sync-easybill-positions.mjs`,
    );
  }
  return p;
}

/** True when a position exists — used to grey out services that aren't priced in easybill yet. */
export function hasPosition(number: string): boolean {
  return positions.has(number);
}

/** Einkaufspreis in Cent. 0, wenn keine Kostendaten vorliegen (Produktion). */
export function costOf(number: string): number {
  return positionCost(number);
}

export const VAT_PERCENT = 19;
